stages:
  - quality

variables:
  GO_VERSION: "1.25"

quality-gate:
  stage: quality
  image: golang:${GO_VERSION}

  cache:
    paths:
      - /go/pkg/mod

  before_script:
    - apt-get update && apt-get install -y make git
    - go install golang.org/x/tools/cmd/goimports@latest
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v2.1.6
    - export PATH=$PATH:$(go env GOPATH)/bin
    - go mod download

  script:
    - make ci

  rules:
    - when: always